### ISSUE TITLE
lastSaleTime: undefined

### ISSUE THREAD

**Issue by KadeStroude** [dsgriffin/opensea-sales-twitter-bot#18]
re: https://github.com/KadeStroude/immutable-x-marketplace-sales-twitter-bot (a fork of your code!)

Hi @dsgriffin, or anyone else - would you mind please assisting me with this?

I am not super familiar with some of the libraries you have used, however made a few changes to the section of 'app.js' where you pull data from OpenSea every 60 seconds:

- Changed the moment(). units to 'toISOOString().' (from 'unix().' - as that is incompatible with the Immutable X API)
- Changed the API url to Immutable X's API (from OpenSea)
- Changed the params such that they were relevant to the new API

I then tried to make some ammendments to the events / response section and the outcome has been my lastSaleTime variable is consistently 'undefined'. Do you know where I am going wrong please?

https://docs.x.immutable.com/reference/get_v1-applications-1

**Comment by dsgriffin** [comment]
hi,

`lastSaleTime` will return `undefined` until the first time a sale comes through - so that's normal unless you're still seeing it `undefined` while sales for your collection are happening. 

i'm not familiar with the immutable x api but best way to confirm you're passing the right data to the endpoint is to add it all here: https://docs.x.immutable.com/reference/get_v1-orders-1 with a  `min_timestamp` that is old enough to give you back some orders

again i'm not sure about immutable x exactly, but you might need to change it from polling every minute as they seem to suggest it's an anti-pattern/susceptible to causing rate-limiting: https://docs.x.immutable.com/docs/api-rate-limiting

**Comment by KadeStroude** [comment]
Thank you very much (and for your latest release which might be helpful too)!
